server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://172.28.144.1:3306/word_learning?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

app:
  jwt:
    secret: YTJmOWE0ZjJjM2I0NTY3ODkwYWJjZGVmMDEyMzQ1Njc4OTBhYmNkZWYwMTIzNDU2Nzg5MGFiY2RlZjAxMjM0
    expiration-ms: 86400000
  level:
    config:
      1: 0
      2: 100
      3: 250
      4: 500
      5: 800
      6: 1200
      7: 1700
      8: 2300
      9: 3000
      10: 4000
